/* Prints the squares of a positive integer and its predecessor */

#include <stdio.h>

int main(void)
{
	long n;

	printf("Enter a value for a positive integer n: ");
	scanf("%ld", &n);
	printf("(n - 1) ^ 2 = %ld\n", (n - 1) * (n - 1));
	printf("      n ^ 2 = %ld\n", n * n);

	/*
	 * Below is the output generated by the calls of printf on my computer:
	 *
	 * Enter a value for a positive integer n: 3037000500
	 * (n - 1) ^ 2 = 9223372030926249001
	 *       n ^ 2 = -9223372036709301616
	 *
	 * long is 64-bit on my 64-bit Linux desktop.
	 */

	return 0;
}
