/* Prints the squares of a positive integer and its predecessor */

#include <stdio.h>

int main(void)
{
	short n;

	printf("Enter a value for a positive integer n: ");
	scanf("%hd", &n);
	printf("(n - 1) ^ 2 = %hd\n", (n - 1) * (n - 1));
	printf("      n ^ 2 = %hd\n", n * n);

	/*
	 * Below is the output generated by the calls of printf on my computer:
	 *
	 * Enter a value for a positive integer n: 182
	 * (n - 1) ^ 2 = 32761
	 *       n ^ 2 = -32412
	 *
	 * short is 16-bit on my 64-bit Linux desktop.
	 */

	return 0;
}
