/* Prints the squares of a positive integer and its predecessor */

#include <stdio.h>

int main(void)
{
	int n;

	printf("Enter a value for a positive integer n: ");
	scanf("%d", &n);
	printf("(n - 1) ^ 2 = %d\n", (n - 1) * (n - 1));
	printf("      n ^ 2 = %d\n", n * n);

	/*
	 * Below is the output generated by the calls of printf on my computer:
	 *
	 * Enter a value for a positive integer n: 46341
	 * (n - 1) ^ 2 = 2147395600
	 *       n ^ 2 = -2147479015
	 *
	 * int is 32-bit on my 64-bit Linux desktop.
	 */

	return 0;
}
